# ---------------------------------------------------------------
#   Site Information And Theme Configuration Settings
#   language: zh-CN
# ---------------------------------------------------------------

## menu 
menu:
- page: 首页
  url: /
  icon: 
- page: 前端
  url: /categories/前端/
  icon: 
- page: 后端
  url: /categories/后端/
  icon: 
- page: 工具
  url: /categories/工具/
  icon: 
- page: 格言
  url: /categories/格言/
  icon: 
- page: 成长日记
  url: /categories/成长日记/
  icon: 

## favicon 
favicon: /favicon.ico

## Feed 
rss: /atom.xml


# 各个小工具的设置

## widgets
widgets:
  - search
  - notification
  - social
  - category
  - archive
  - tagcloud
  - friends

## 搜索
jsonContent:
  searchLocal: true
  searchGoogle: false
  posts:
    title: true
    text: true
    content: true
    categories: false
    tags: false

## 网站公告设置
notification: |-
            <p>本博客用于对博主工作中遇到的一些问题及解决方案的记录和总结，便于自己以后查询也帮助一些遇到同样问题并且看到本博客的人解决问题!
            <div style="margin-bottom:10px">部分内容来源于网络，可能未注明出处，如有侵权，请联系博主删除，邮箱：<a target='_blank' href="http://mail.qq.com/cgi-bin/qm_share?t=qm_mailme&email=KB4RGxkQHB0aEGhZWQZLR0U">wangheng3751@qq.com</a></div>
            <p>如有问题，可加入博主个人技术讨论QQ群：516032289</p>
            </p>

## 社交设置
social:
 - name: Github
   icon: git
   href: //github.com/wangheng3751
 - name: 邮箱
   icon: envelope-o
   href: http://mail.qq.com/cgi-bin/qm_share?t=qm_mailme&email=KB4RGxkQHB0aEGhZWQZLR0U
 - name: 联系QQ
   icon: qq
   href: http://wpa.qq.com/msgrd?v=3&uin=693184528&site=qq&menu=yes
 - name: QQ群
   icon: users
   href: https://jq.qq.com/?_wv=1027&k=5j2JBvV

## 文章分类设置
cate_config:
   show_count: true
   show_current: true

## 文章归档设置
arch_config:
   type: 'monthly'
   show_count: true
   order: -1

## 友链设置
links:
  - 我的简书: https://www.jianshu.com/u/95064c5d51c7


# 主题自定义个性化配置

## 网站宣传语
branding: 学问之道无穷，而总以有「恒」为主

## 设置banner背景图片
banner:
    img: https://github.com/wangheng3751/my-resources/blob/master/images/blog-banner.jpg?raw=true

## 缩略图自定义随机图片
defaultImgs:
  -

## 截取文章首页描述字数
excerptLength: 120

## 代码高亮配置
highlightTheme: 

## ICON配置
fontAwesome: //cdn.bootcss.com/font-awesome/4.7.0/css/font-awesome.min.css

## 文章过期提醒功能
warning:
  days: 300
  text: '本文于%d天之前发表，文中内容可能已经过时。'

## 文章内声明
declaration:
  enable: true
  title: '转载声明'
  tip: |-
      商业转载请联系作者获得授权,非商业转载请注明出处 © <a href="https://wangheng3751.github.io/" target="_blank">有恒则成</a>


## 主题评论

### gitment
gitment:
  enable: false
  owner: 
  repo: 
  client_id: 
  client_secret: 
  perPage: 10

### 来必力
livere: 
  enable: true
  livere_uid: MTAyMC8zMzMwMi85ODU5

### 友言评论
uyan:
  enable: false
  uyan_id: 1966422

### Disqus评论
disqus:
  enable: false
  shortname: snippet
  count: false

## 网站访问统计

### 网盟CNZZ统计
#cnzz_analytics: 1263868967

### 百度统计
baidu_analytics: 

### 谷歌统计
google_analytics: 

### 腾讯分析
tencent_analytics: 64969916

### 百度文章推送
baidu_push:

#网站主题配置
since: 2018
robot: 'all' ### 控制搜索引擎的抓取和索引编制行为，默认为all
version: 1.2.1

language: zh-CN

#自定义
blog_name: 有恒则成 